### ISSUE TITLE
Navigation links broken

### ISSUE THREAD

**Issue by jaselmore** [JGallegos1/Quality-Assurance-Assignment#1]
Links on navigation are not linked to actual pages. Redirected to "File not found" page.
Severity/Priority: Wrong result/Must fix before product release
Browser: Firefox 42
Expected result: When clicking on a link in the navigation bar, user will be redirected to the specified page
Actual: When clicking on a link in the navigation bar, user is redirected to the "File not found" page.
Steps to reproduce: Make sure links are linked to actual pages

**Comment by JGallegos1** [comment]
Fixed in 5f8bc0f23150683575d450f887f87178a066642e
