### ISSUE TITLE
<meta charset> tag

### ISSUE THREAD

**Issue by jaselmore** [JGallegos1/Quality-Assurance-Assignment#10]
The < meta charset > tag reads <meta charset="urf-8">
Severity/Priority: May produce wrong result/Should fix when time permits
Environment: Within the code
Expected: Should read <meta charset="UTF-8">
Actual: < meta charset="urf-8" >
Steps to Reproduce: Change "urf-8" to "UTF-8"

**Comment by JGallegos1** [comment]
Fixed in dca2a8d8c4a51bfe3a7a168c50d02b7009c76284
