### ISSUE TITLE
Missing copyright notice

### ISSUE THREAD

**Issue by jaselmore** [JGallegos1/Quality-Assurance-Assignment#3]
All pages are missing a copyright notice
Severity/Priority: Minor problem/Would like to fix, but product can be released as is
Browser: Firefox 42
Expected: There will be a copyright notice on each page
Actual: There is no copyright notice on any pages
Steps to Reproduce: Add a copyright notice to each page

**Comment by JGallegos1** [comment]
Fixed in 91300910da2491e2857a59d2a61b881dc4e2b3d0

**Comment by JGallegos1** [comment]
91300910da2491e2857a59d2a61b881dc4e2b3d0

**Comment by JGallegos1** [comment]
Fixed in 91300910da2491e2857a59d2a61b881dc4e2b3d0
