### ISSUE TITLE
Pages do not have a link to log in

### ISSUE THREAD

**Issue by jaselmore** [JGallegos1/Quality-Assurance-Assignment#6]
All pages - excluding the login page (index) do not contain a link to login when not logged in
Severity/Priority - Operational error/Must fix before product release
Browser: Firefox 42
Expected: There will be a link to login on each page when user is not logged in
Actual: There is only the option to login on the index page
Steps to be Reproduced: Add a link to login on each page when user is not logged in

**Comment by JGallegos1** [comment]
fixed in 3dcc927aaefb76ebc787d42042f8e3859b082db4
